# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Foxmayn.ffc
PackageVersion: 1.16.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ffc.exe
  PortableCommandAlias: ffc
UpgradeBehavior: install
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nasroykh/foxmayn_frappe_cli/releases/download/v1.16.1/ffc_1.16.1_windows_amd64.zip
  InstallerSha256: 036BCF7EAB1EDAE5DF446BC158BDF22F8EBCB064067932885C2BAB33F5775AD4
- Architecture: arm64
  InstallerUrl: https://github.com/nasroykh/foxmayn_frappe_cli/releases/download/v1.16.1/ffc_1.16.1_windows_arm64.zip
  InstallerSha256: C7A3651F53192DBC86E3F4C69B985880A196050C77DD539363542C9C7BEAF2B7
ManifestType: installer
ManifestVersion: 1.12.0
